#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransparenciaDAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_Defensoria_Transparencia")]
	public partial class TransparenciaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TransparenciaDataContext() : 
				base(global::TransparenciaDAO.Properties.Settings.Default.bd_Defensoria_TransparenciaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public TransparenciaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransparenciaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransparenciaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransparenciaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vw_contratos_convenio> vw_contratos_convenios
		{
			get
			{
				return this.GetTable<vw_contratos_convenio>();
			}
		}
		
		public System.Data.Linq.Table<vw_folha_pagamento_servidor> vw_folha_pagamento_servidors
		{
			get
			{
				return this.GetTable<vw_folha_pagamento_servidor>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_comissao_servidor> vw_cargo_comissao_servidors
		{
			get
			{
				return this.GetTable<vw_cargo_comissao_servidor>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_defensor_servidor> vw_cargo_defensor_servidors
		{
			get
			{
				return this.GetTable<vw_cargo_defensor_servidor>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_efetivo_servidor> vw_cargo_efetivo_servidors
		{
			get
			{
				return this.GetTable<vw_cargo_efetivo_servidor>();
			}
		}
		
		public System.Data.Linq.Table<vw_folha_subsidio> vw_folha_subsidios
		{
			get
			{
				return this.GetTable<vw_folha_subsidio>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_efetivo_vencimento> vw_cargo_efetivo_vencimentos
		{
			get
			{
				return this.GetTable<vw_cargo_efetivo_vencimento>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_comissionado_vencimento> vw_cargo_comissionado_vencimentos
		{
			get
			{
				return this.GetTable<vw_cargo_comissionado_vencimento>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_contratos_convenios")]
	public partial class vw_contratos_convenio
	{
		
		private int _codigoProcesso;
		
		private string _nomeArquivoPDF;
		
		private string _ano;
		
		private string _numeroProcesso;
		
		private string _contratada;
		
		private string _modalidade;
		
		private string _finalizado;
		
		private string _vigenciaInicial;
		
		private string _vigenciaFinal;
		
		private string _dataContrato;
		
		private string _vigenciaProrrogada;
		
		private string _objeto;
		
		public vw_contratos_convenio()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="Int NOT NULL")]
		public int codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeArquivoPDF", DbType="VarChar(500)")]
		public string nomeArquivoPDF
		{
			get
			{
				return this._nomeArquivoPDF;
			}
			set
			{
				if ((this._nomeArquivoPDF != value))
				{
					this._nomeArquivoPDF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="VarChar(4)")]
		public string ano
		{
			get
			{
				return this._ano;
			}
			set
			{
				if ((this._ano != value))
				{
					this._ano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroProcesso", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string numeroProcesso
		{
			get
			{
				return this._numeroProcesso;
			}
			set
			{
				if ((this._numeroProcesso != value))
				{
					this._numeroProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contratada", DbType="VarChar(255)")]
		public string contratada
		{
			get
			{
				return this._contratada;
			}
			set
			{
				if ((this._contratada != value))
				{
					this._contratada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modalidade", DbType="VarChar(255)")]
		public string modalidade
		{
			get
			{
				return this._modalidade;
			}
			set
			{
				if ((this._modalidade != value))
				{
					this._modalidade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finalizado", DbType="VarChar(3)")]
		public string finalizado
		{
			get
			{
				return this._finalizado;
			}
			set
			{
				if ((this._finalizado != value))
				{
					this._finalizado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigenciaInicial", DbType="Char(30)")]
		public string vigenciaInicial
		{
			get
			{
				return this._vigenciaInicial;
			}
			set
			{
				if ((this._vigenciaInicial != value))
				{
					this._vigenciaInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigenciaFinal", DbType="Char(30)")]
		public string vigenciaFinal
		{
			get
			{
				return this._vigenciaFinal;
			}
			set
			{
				if ((this._vigenciaFinal != value))
				{
					this._vigenciaFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataContrato", DbType="Char(30)")]
		public string dataContrato
		{
			get
			{
				return this._dataContrato;
			}
			set
			{
				if ((this._dataContrato != value))
				{
					this._dataContrato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigenciaProrrogada", DbType="Char(30)")]
		public string vigenciaProrrogada
		{
			get
			{
				return this._vigenciaProrrogada;
			}
			set
			{
				if ((this._vigenciaProrrogada != value))
				{
					this._vigenciaProrrogada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objeto", DbType="VarChar(5000)")]
		public string objeto
		{
			get
			{
				return this._objeto;
			}
			set
			{
				if ((this._objeto != value))
				{
					this._objeto = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_folha_pagamento_servidor")]
	public partial class vw_folha_pagamento_servidor
	{
		
		private string _Mês_Competência;
		
		private System.Nullable<int> _Ano_Competência;
		
		private string _Matrícula;
		
		private string _Nome_Beneficiário;
		
		private string _Cargo;
		
		private string _Classe;
		
		private string _Cargo_Comissão;
		
		private System.Nullable<decimal> _Vencimento;
		
		private System.Nullable<decimal> _Subsidio;
		
		private System.Nullable<decimal> _Vantagens_Pessoais;
		
		private System.Nullable<decimal> _Vantagens_Cargo;
		
		private System.Nullable<decimal> _Férias;
		
		private System.Nullable<decimal> _Décimo_Salário;
		
		private System.Nullable<decimal> _Total_Créditos;
		
		private System.Nullable<decimal> _Previdência;
		
		private System.Nullable<decimal> _Imposto;
		
		private System.Nullable<decimal> _Total_Desconto;
		
		private System.Nullable<decimal> _Total_Líquido;
		
		private System.Nullable<decimal> _Indenizações;
		
		public vw_folha_pagamento_servidor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mês Competência]", Storage="_Mês_Competência", DbType="VarChar(15)")]
		public string Mês_Competência
		{
			get
			{
				return this._Mês_Competência;
			}
			set
			{
				if ((this._Mês_Competência != value))
				{
					this._Mês_Competência = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ano Competência]", Storage="_Ano_Competência", DbType="Int")]
		public System.Nullable<int> Ano_Competência
		{
			get
			{
				return this._Ano_Competência;
			}
			set
			{
				if ((this._Ano_Competência != value))
				{
					this._Ano_Competência = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matrícula", DbType="VarChar(255)")]
		public string Matrícula
		{
			get
			{
				return this._Matrícula;
			}
			set
			{
				if ((this._Matrícula != value))
				{
					this._Matrícula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nome Beneficiário]", Storage="_Nome_Beneficiário", DbType="VarChar(255)")]
		public string Nome_Beneficiário
		{
			get
			{
				return this._Nome_Beneficiário;
			}
			set
			{
				if ((this._Nome_Beneficiário != value))
				{
					this._Nome_Beneficiário = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(255)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classe", DbType="VarChar(255)")]
		public string Classe
		{
			get
			{
				return this._Classe;
			}
			set
			{
				if ((this._Classe != value))
				{
					this._Classe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cargo Comissão]", Storage="_Cargo_Comissão", DbType="VarChar(255)")]
		public string Cargo_Comissão
		{
			get
			{
				return this._Cargo_Comissão;
			}
			set
			{
				if ((this._Cargo_Comissão != value))
				{
					this._Cargo_Comissão = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vencimento", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Vencimento
		{
			get
			{
				return this._Vencimento;
			}
			set
			{
				if ((this._Vencimento != value))
				{
					this._Vencimento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subsidio", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Subsidio
		{
			get
			{
				return this._Subsidio;
			}
			set
			{
				if ((this._Subsidio != value))
				{
					this._Subsidio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vantagens Pessoais]", Storage="_Vantagens_Pessoais", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Vantagens_Pessoais
		{
			get
			{
				return this._Vantagens_Pessoais;
			}
			set
			{
				if ((this._Vantagens_Pessoais != value))
				{
					this._Vantagens_Pessoais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vantagens Cargo]", Storage="_Vantagens_Cargo", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Vantagens_Cargo
		{
			get
			{
				return this._Vantagens_Cargo;
			}
			set
			{
				if ((this._Vantagens_Cargo != value))
				{
					this._Vantagens_Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Férias", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Férias
		{
			get
			{
				return this._Férias;
			}
			set
			{
				if ((this._Férias != value))
				{
					this._Férias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Décimo Salário]", Storage="_Décimo_Salário", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Décimo_Salário
		{
			get
			{
				return this._Décimo_Salário;
			}
			set
			{
				if ((this._Décimo_Salário != value))
				{
					this._Décimo_Salário = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total Créditos]", Storage="_Total_Créditos", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Total_Créditos
		{
			get
			{
				return this._Total_Créditos;
			}
			set
			{
				if ((this._Total_Créditos != value))
				{
					this._Total_Créditos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Previdência", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Previdência
		{
			get
			{
				return this._Previdência;
			}
			set
			{
				if ((this._Previdência != value))
				{
					this._Previdência = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imposto", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Imposto
		{
			get
			{
				return this._Imposto;
			}
			set
			{
				if ((this._Imposto != value))
				{
					this._Imposto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total Desconto]", Storage="_Total_Desconto", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Total_Desconto
		{
			get
			{
				return this._Total_Desconto;
			}
			set
			{
				if ((this._Total_Desconto != value))
				{
					this._Total_Desconto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total Líquido]", Storage="_Total_Líquido", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Total_Líquido
		{
			get
			{
				return this._Total_Líquido;
			}
			set
			{
				if ((this._Total_Líquido != value))
				{
					this._Total_Líquido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indenizações", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Indenizações
		{
			get
			{
				return this._Indenizações;
			}
			set
			{
				if ((this._Indenizações != value))
				{
					this._Indenizações = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_comissao_servidor")]
	public partial class vw_cargo_comissao_servidor
	{
		
		private string _grupo;
		
		private string _simbolo;
		
		private string _cargo;
		
		private System.Nullable<int> _vagasPrevistas;
		
		public vw_cargo_comissao_servidor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupo", DbType="VarChar(255)")]
		public string grupo
		{
			get
			{
				return this._grupo;
			}
			set
			{
				if ((this._grupo != value))
				{
					this._grupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_simbolo", DbType="VarChar(255)")]
		public string simbolo
		{
			get
			{
				return this._simbolo;
			}
			set
			{
				if ((this._simbolo != value))
				{
					this._simbolo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(255)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this._cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vagasPrevistas", DbType="Int")]
		public System.Nullable<int> vagasPrevistas
		{
			get
			{
				return this._vagasPrevistas;
			}
			set
			{
				if ((this._vagasPrevistas != value))
				{
					this._vagasPrevistas = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_defensor_servidor")]
	public partial class vw_cargo_defensor_servidor
	{
		
		private string _carreira;
		
		private string _cargo;
		
		private string _classe;
		
		private string _simbolo;
		
		private System.Nullable<int> _vagasPreenchidas;
		
		private System.Nullable<int> _previstas;
		
		private string _nomeBeneficiario;
		
		private string _matricula;
		
		public vw_cargo_defensor_servidor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carreira", DbType="VarChar(255)")]
		public string carreira
		{
			get
			{
				return this._carreira;
			}
			set
			{
				if ((this._carreira != value))
				{
					this._carreira = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(255)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this._cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe", DbType="VarChar(255)")]
		public string classe
		{
			get
			{
				return this._classe;
			}
			set
			{
				if ((this._classe != value))
				{
					this._classe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_simbolo", DbType="VarChar(255)")]
		public string simbolo
		{
			get
			{
				return this._simbolo;
			}
			set
			{
				if ((this._simbolo != value))
				{
					this._simbolo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vagasPreenchidas", DbType="Int")]
		public System.Nullable<int> vagasPreenchidas
		{
			get
			{
				return this._vagasPreenchidas;
			}
			set
			{
				if ((this._vagasPreenchidas != value))
				{
					this._vagasPreenchidas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_previstas", DbType="Int")]
		public System.Nullable<int> previstas
		{
			get
			{
				return this._previstas;
			}
			set
			{
				if ((this._previstas != value))
				{
					this._previstas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeBeneficiario", DbType="VarChar(255)")]
		public string nomeBeneficiario
		{
			get
			{
				return this._nomeBeneficiario;
			}
			set
			{
				if ((this._nomeBeneficiario != value))
				{
					this._nomeBeneficiario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="VarChar(255)")]
		public string matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					this._matricula = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_efetivo_servidor")]
	public partial class vw_cargo_efetivo_servidor
	{
		
		private string _carreira;
		
		private System.Nullable<int> _quantitativo;
		
		private string _classe;
		
		public vw_cargo_efetivo_servidor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carreira", DbType="VarChar(255)")]
		public string carreira
		{
			get
			{
				return this._carreira;
			}
			set
			{
				if ((this._carreira != value))
				{
					this._carreira = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantitativo", DbType="Int")]
		public System.Nullable<int> quantitativo
		{
			get
			{
				return this._quantitativo;
			}
			set
			{
				if ((this._quantitativo != value))
				{
					this._quantitativo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe", DbType="VarChar(255)")]
		public string classe
		{
			get
			{
				return this._classe;
			}
			set
			{
				if ((this._classe != value))
				{
					this._classe = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_folha_subsidio")]
	public partial class vw_folha_subsidio
	{
		
		private decimal _id;
		
		private string _descricaoClasse;
		
		private string _tipoServidor;
		
		private System.Nullable<decimal> _valorReajuste;
		
		private System.Nullable<int> _anoCompetencia;
		
		private System.Nullable<int> _vagasPrevistas;
		
		public vw_folha_subsidio()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Decimal(19,0) NOT NULL")]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoClasse", DbType="VarChar(255)")]
		public string descricaoClasse
		{
			get
			{
				return this._descricaoClasse;
			}
			set
			{
				if ((this._descricaoClasse != value))
				{
					this._descricaoClasse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoServidor", DbType="VarChar(255)")]
		public string tipoServidor
		{
			get
			{
				return this._tipoServidor;
			}
			set
			{
				if ((this._tipoServidor != value))
				{
					this._tipoServidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorReajuste", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> valorReajuste
		{
			get
			{
				return this._valorReajuste;
			}
			set
			{
				if ((this._valorReajuste != value))
				{
					this._valorReajuste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoCompetencia", DbType="Int")]
		public System.Nullable<int> anoCompetencia
		{
			get
			{
				return this._anoCompetencia;
			}
			set
			{
				if ((this._anoCompetencia != value))
				{
					this._anoCompetencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vagasPrevistas", DbType="Int")]
		public System.Nullable<int> vagasPrevistas
		{
			get
			{
				return this._vagasPrevistas;
			}
			set
			{
				if ((this._vagasPrevistas != value))
				{
					this._vagasPrevistas = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_efetivo_vencimento")]
	public partial class vw_cargo_efetivo_vencimento
	{
		
		private System.Nullable<int> _anoCompetencia;
		
		private string _cargo;
		
		private string _classe;
		
		private System.Nullable<decimal> _vencimentoBase;
		
		public vw_cargo_efetivo_vencimento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoCompetencia", DbType="Int")]
		public System.Nullable<int> anoCompetencia
		{
			get
			{
				return this._anoCompetencia;
			}
			set
			{
				if ((this._anoCompetencia != value))
				{
					this._anoCompetencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(255)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this._cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe", DbType="VarChar(255)")]
		public string classe
		{
			get
			{
				return this._classe;
			}
			set
			{
				if ((this._classe != value))
				{
					this._classe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimentoBase", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> vencimentoBase
		{
			get
			{
				return this._vencimentoBase;
			}
			set
			{
				if ((this._vencimentoBase != value))
				{
					this._vencimentoBase = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_comissionado_vencimento")]
	public partial class vw_cargo_comissionado_vencimento
	{
		
		private System.Nullable<int> _anoCompetencia;
		
		private string _descricaoClasse;
		
		private string _tipoServidor;
		
		private System.Nullable<decimal> _valorReajuste;
		
		private System.Nullable<decimal> _gratificacao;
		
		private string _percentual;
		
		public vw_cargo_comissionado_vencimento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoCompetencia", DbType="Int")]
		public System.Nullable<int> anoCompetencia
		{
			get
			{
				return this._anoCompetencia;
			}
			set
			{
				if ((this._anoCompetencia != value))
				{
					this._anoCompetencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoClasse", DbType="VarChar(255)")]
		public string descricaoClasse
		{
			get
			{
				return this._descricaoClasse;
			}
			set
			{
				if ((this._descricaoClasse != value))
				{
					this._descricaoClasse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoServidor", DbType="VarChar(255)")]
		public string tipoServidor
		{
			get
			{
				return this._tipoServidor;
			}
			set
			{
				if ((this._tipoServidor != value))
				{
					this._tipoServidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorReajuste", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> valorReajuste
		{
			get
			{
				return this._valorReajuste;
			}
			set
			{
				if ((this._valorReajuste != value))
				{
					this._valorReajuste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gratificacao", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> gratificacao
		{
			get
			{
				return this._gratificacao;
			}
			set
			{
				if ((this._gratificacao != value))
				{
					this._gratificacao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percentual", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string percentual
		{
			get
			{
				return this._percentual;
			}
			set
			{
				if ((this._percentual != value))
				{
					this._percentual = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
