#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransparenciaDAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_Defensoria_Transparencia")]
	public partial class TransparenciaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TransparenciaDataContext() : 
				base(global::TransparenciaDAO.Properties.Settings.Default.bd_Defensoria_TransparenciaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public TransparenciaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransparenciaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransparenciaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransparenciaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vw_contratos_convenio> vw_contratos_convenios
		{
			get
			{
				return this.GetTable<vw_contratos_convenio>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_comissao_servidor> vw_cargo_comissao_servidors
		{
			get
			{
				return this.GetTable<vw_cargo_comissao_servidor>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_defensor_servidor> vw_cargo_defensor_servidors
		{
			get
			{
				return this.GetTable<vw_cargo_defensor_servidor>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_efetivo_servidor> vw_cargo_efetivo_servidors
		{
			get
			{
				return this.GetTable<vw_cargo_efetivo_servidor>();
			}
		}
		
		public System.Data.Linq.Table<vw_folha_subsidio> vw_folha_subsidios
		{
			get
			{
				return this.GetTable<vw_folha_subsidio>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_efetivo_vencimento> vw_cargo_efetivo_vencimentos
		{
			get
			{
				return this.GetTable<vw_cargo_efetivo_vencimento>();
			}
		}
		
		public System.Data.Linq.Table<vw_cargo_comissionado_vencimento> vw_cargo_comissionado_vencimentos
		{
			get
			{
				return this.GetTable<vw_cargo_comissionado_vencimento>();
			}
		}
		
		public System.Data.Linq.Table<vw_licitacoes_legislacao> vw_licitacoes_legislacaos
		{
			get
			{
				return this.GetTable<vw_licitacoes_legislacao>();
			}
		}
		
		public System.Data.Linq.Table<vw_licitacoes_aviso> vw_licitacoes_avisos
		{
			get
			{
				return this.GetTable<vw_licitacoes_aviso>();
			}
		}
		
		public System.Data.Linq.Table<vw_licitacoes_tomada_de_preco> vw_licitacoes_tomada_de_precos
		{
			get
			{
				return this.GetTable<vw_licitacoes_tomada_de_preco>();
			}
		}
		
		public System.Data.Linq.Table<vw_licitacoes_concorrencia_publica> vw_licitacoes_concorrencia_publicas
		{
			get
			{
				return this.GetTable<vw_licitacoes_concorrencia_publica>();
			}
		}
		
		public System.Data.Linq.Table<vw_licitacoes_pregao_presencial> vw_licitacoes_pregao_presencials
		{
			get
			{
				return this.GetTable<vw_licitacoes_pregao_presencial>();
			}
		}
		
		public System.Data.Linq.Table<vw_licitacoes_pregao_presencial_registro_preco> vw_licitacoes_pregao_presencial_registro_precos
		{
			get
			{
				return this.GetTable<vw_licitacoes_pregao_presencial_registro_preco>();
			}
		}
		
		public System.Data.Linq.Table<vw_licitacoes_pregao_eletronico> vw_licitacoes_pregao_eletronicos
		{
			get
			{
				return this.GetTable<vw_licitacoes_pregao_eletronico>();
			}
		}
		
		public System.Data.Linq.Table<vw_licitacoes_ata_registro_preco> vw_licitacoes_ata_registro_precos
		{
			get
			{
				return this.GetTable<vw_licitacoes_ata_registro_preco>();
			}
		}
		
		public System.Data.Linq.Table<vw_licitacoes_cadastro_fornecedore> vw_licitacoes_cadastro_fornecedores
		{
			get
			{
				return this.GetTable<vw_licitacoes_cadastro_fornecedore>();
			}
		}
		
		public System.Data.Linq.Table<vw_folha_pagamento_servidor> vw_folha_pagamento_servidors
		{
			get
			{
				return this.GetTable<vw_folha_pagamento_servidor>();
			}
		}
		
		public System.Data.Linq.Table<vw_servidore> vw_servidores
		{
			get
			{
				return this.GetTable<vw_servidore>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_contratos_convenios")]
	public partial class vw_contratos_convenio
	{
		
		private int _codigoProcesso;
		
		private string _nomeArquivoPDF;
		
		private string _ano;
		
		private string _numeroProcesso;
		
		private string _contratada;
		
		private string _modalidade;
		
		private string _finalizado;
		
		private string _vigenciaInicial;
		
		private string _vigenciaFinal;
		
		private string _dataContrato;
		
		private string _vigenciaProrrogada;
		
		private string _objeto;
		
		public vw_contratos_convenio()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="Int NOT NULL")]
		public int codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeArquivoPDF", DbType="VarChar(500)")]
		public string nomeArquivoPDF
		{
			get
			{
				return this._nomeArquivoPDF;
			}
			set
			{
				if ((this._nomeArquivoPDF != value))
				{
					this._nomeArquivoPDF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="VarChar(4)")]
		public string ano
		{
			get
			{
				return this._ano;
			}
			set
			{
				if ((this._ano != value))
				{
					this._ano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroProcesso", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string numeroProcesso
		{
			get
			{
				return this._numeroProcesso;
			}
			set
			{
				if ((this._numeroProcesso != value))
				{
					this._numeroProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contratada", DbType="VarChar(255)")]
		public string contratada
		{
			get
			{
				return this._contratada;
			}
			set
			{
				if ((this._contratada != value))
				{
					this._contratada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modalidade", DbType="VarChar(255)")]
		public string modalidade
		{
			get
			{
				return this._modalidade;
			}
			set
			{
				if ((this._modalidade != value))
				{
					this._modalidade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finalizado", DbType="VarChar(3)")]
		public string finalizado
		{
			get
			{
				return this._finalizado;
			}
			set
			{
				if ((this._finalizado != value))
				{
					this._finalizado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigenciaInicial", DbType="Char(30)")]
		public string vigenciaInicial
		{
			get
			{
				return this._vigenciaInicial;
			}
			set
			{
				if ((this._vigenciaInicial != value))
				{
					this._vigenciaInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigenciaFinal", DbType="Char(30)")]
		public string vigenciaFinal
		{
			get
			{
				return this._vigenciaFinal;
			}
			set
			{
				if ((this._vigenciaFinal != value))
				{
					this._vigenciaFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataContrato", DbType="Char(30)")]
		public string dataContrato
		{
			get
			{
				return this._dataContrato;
			}
			set
			{
				if ((this._dataContrato != value))
				{
					this._dataContrato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigenciaProrrogada", DbType="Char(30)")]
		public string vigenciaProrrogada
		{
			get
			{
				return this._vigenciaProrrogada;
			}
			set
			{
				if ((this._vigenciaProrrogada != value))
				{
					this._vigenciaProrrogada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objeto", DbType="VarChar(5000)")]
		public string objeto
		{
			get
			{
				return this._objeto;
			}
			set
			{
				if ((this._objeto != value))
				{
					this._objeto = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_comissao_servidor")]
	public partial class vw_cargo_comissao_servidor
	{
		
		private string _grupo;
		
		private string _simbolo;
		
		private string _cargo;
		
		private System.Nullable<int> _vagasPrevistas;
		
		public vw_cargo_comissao_servidor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupo", DbType="VarChar(255)")]
		public string grupo
		{
			get
			{
				return this._grupo;
			}
			set
			{
				if ((this._grupo != value))
				{
					this._grupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_simbolo", DbType="VarChar(255)")]
		public string simbolo
		{
			get
			{
				return this._simbolo;
			}
			set
			{
				if ((this._simbolo != value))
				{
					this._simbolo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(255)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this._cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vagasPrevistas", DbType="Int")]
		public System.Nullable<int> vagasPrevistas
		{
			get
			{
				return this._vagasPrevistas;
			}
			set
			{
				if ((this._vagasPrevistas != value))
				{
					this._vagasPrevistas = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_defensor_servidor")]
	public partial class vw_cargo_defensor_servidor
	{
		
		private string _carreira;
		
		private string _cargo;
		
		private string _classe;
		
		private string _simbolo;
		
		private System.Nullable<int> _vagasPreenchidas;
		
		private System.Nullable<int> _previstas;
		
		private string _nomeBeneficiario;
		
		private string _matricula;
		
		public vw_cargo_defensor_servidor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carreira", DbType="VarChar(255)")]
		public string carreira
		{
			get
			{
				return this._carreira;
			}
			set
			{
				if ((this._carreira != value))
				{
					this._carreira = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(255)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this._cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe", DbType="VarChar(255)")]
		public string classe
		{
			get
			{
				return this._classe;
			}
			set
			{
				if ((this._classe != value))
				{
					this._classe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_simbolo", DbType="VarChar(255)")]
		public string simbolo
		{
			get
			{
				return this._simbolo;
			}
			set
			{
				if ((this._simbolo != value))
				{
					this._simbolo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vagasPreenchidas", DbType="Int")]
		public System.Nullable<int> vagasPreenchidas
		{
			get
			{
				return this._vagasPreenchidas;
			}
			set
			{
				if ((this._vagasPreenchidas != value))
				{
					this._vagasPreenchidas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_previstas", DbType="Int")]
		public System.Nullable<int> previstas
		{
			get
			{
				return this._previstas;
			}
			set
			{
				if ((this._previstas != value))
				{
					this._previstas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeBeneficiario", DbType="VarChar(255)")]
		public string nomeBeneficiario
		{
			get
			{
				return this._nomeBeneficiario;
			}
			set
			{
				if ((this._nomeBeneficiario != value))
				{
					this._nomeBeneficiario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="VarChar(255)")]
		public string matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					this._matricula = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_efetivo_servidor")]
	public partial class vw_cargo_efetivo_servidor
	{
		
		private string _carreira;
		
		private System.Nullable<int> _quantitativo;
		
		private string _classe;
		
		public vw_cargo_efetivo_servidor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carreira", DbType="VarChar(255)")]
		public string carreira
		{
			get
			{
				return this._carreira;
			}
			set
			{
				if ((this._carreira != value))
				{
					this._carreira = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantitativo", DbType="Int")]
		public System.Nullable<int> quantitativo
		{
			get
			{
				return this._quantitativo;
			}
			set
			{
				if ((this._quantitativo != value))
				{
					this._quantitativo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe", DbType="VarChar(255)")]
		public string classe
		{
			get
			{
				return this._classe;
			}
			set
			{
				if ((this._classe != value))
				{
					this._classe = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_folha_subsidio")]
	public partial class vw_folha_subsidio
	{
		
		private decimal _id;
		
		private string _descricaoClasse;
		
		private string _tipoServidor;
		
		private System.Nullable<decimal> _valorReajuste;
		
		private System.Nullable<int> _anoCompetencia;
		
		private System.Nullable<int> _vagasPrevistas;
		
		public vw_folha_subsidio()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Decimal(19,0) NOT NULL")]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoClasse", DbType="VarChar(255)")]
		public string descricaoClasse
		{
			get
			{
				return this._descricaoClasse;
			}
			set
			{
				if ((this._descricaoClasse != value))
				{
					this._descricaoClasse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoServidor", DbType="VarChar(255)")]
		public string tipoServidor
		{
			get
			{
				return this._tipoServidor;
			}
			set
			{
				if ((this._tipoServidor != value))
				{
					this._tipoServidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorReajuste", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> valorReajuste
		{
			get
			{
				return this._valorReajuste;
			}
			set
			{
				if ((this._valorReajuste != value))
				{
					this._valorReajuste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoCompetencia", DbType="Int")]
		public System.Nullable<int> anoCompetencia
		{
			get
			{
				return this._anoCompetencia;
			}
			set
			{
				if ((this._anoCompetencia != value))
				{
					this._anoCompetencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vagasPrevistas", DbType="Int")]
		public System.Nullable<int> vagasPrevistas
		{
			get
			{
				return this._vagasPrevistas;
			}
			set
			{
				if ((this._vagasPrevistas != value))
				{
					this._vagasPrevistas = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_efetivo_vencimento")]
	public partial class vw_cargo_efetivo_vencimento
	{
		
		private System.Nullable<int> _anoCompetencia;
		
		private string _cargo;
		
		private string _classe;
		
		private System.Nullable<decimal> _vencimentoBase;
		
		public vw_cargo_efetivo_vencimento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoCompetencia", DbType="Int")]
		public System.Nullable<int> anoCompetencia
		{
			get
			{
				return this._anoCompetencia;
			}
			set
			{
				if ((this._anoCompetencia != value))
				{
					this._anoCompetencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(255)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this._cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe", DbType="VarChar(255)")]
		public string classe
		{
			get
			{
				return this._classe;
			}
			set
			{
				if ((this._classe != value))
				{
					this._classe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimentoBase", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> vencimentoBase
		{
			get
			{
				return this._vencimentoBase;
			}
			set
			{
				if ((this._vencimentoBase != value))
				{
					this._vencimentoBase = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_cargo_comissionado_vencimento")]
	public partial class vw_cargo_comissionado_vencimento
	{
		
		private System.Nullable<int> _anoCompetencia;
		
		private string _descricaoClasse;
		
		private string _tipoServidor;
		
		private System.Nullable<decimal> _valorReajuste;
		
		private System.Nullable<decimal> _gratificacao;
		
		private string _percentual;
		
		public vw_cargo_comissionado_vencimento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoCompetencia", DbType="Int")]
		public System.Nullable<int> anoCompetencia
		{
			get
			{
				return this._anoCompetencia;
			}
			set
			{
				if ((this._anoCompetencia != value))
				{
					this._anoCompetencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoClasse", DbType="VarChar(255)")]
		public string descricaoClasse
		{
			get
			{
				return this._descricaoClasse;
			}
			set
			{
				if ((this._descricaoClasse != value))
				{
					this._descricaoClasse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoServidor", DbType="VarChar(255)")]
		public string tipoServidor
		{
			get
			{
				return this._tipoServidor;
			}
			set
			{
				if ((this._tipoServidor != value))
				{
					this._tipoServidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorReajuste", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> valorReajuste
		{
			get
			{
				return this._valorReajuste;
			}
			set
			{
				if ((this._valorReajuste != value))
				{
					this._valorReajuste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gratificacao", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> gratificacao
		{
			get
			{
				return this._gratificacao;
			}
			set
			{
				if ((this._gratificacao != value))
				{
					this._gratificacao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percentual", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string percentual
		{
			get
			{
				return this._percentual;
			}
			set
			{
				if ((this._percentual != value))
				{
					this._percentual = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_licitacoes_legislacao")]
	public partial class vw_licitacoes_legislacao
	{
		
		private string _menu;
		
		private System.Nullable<int> _anoProcesso;
		
		private string _descricaoProcesso;
		
		private string _observacoesProcesso;
		
		private string _situacaoProcesso;
		
		private string _dataProcesso;
		
		private string _codigoProcesso;
		
		private string _caminhoProcesso;
		
		private string _descricaoArquivoDownload;
		
		public vw_licitacoes_legislacao()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					this._menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoProcesso", DbType="Int")]
		public System.Nullable<int> anoProcesso
		{
			get
			{
				return this._anoProcesso;
			}
			set
			{
				if ((this._anoProcesso != value))
				{
					this._anoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoProcesso", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descricaoProcesso
		{
			get
			{
				return this._descricaoProcesso;
			}
			set
			{
				if ((this._descricaoProcesso != value))
				{
					this._descricaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoesProcesso", DbType="VarChar(MAX)")]
		public string observacoesProcesso
		{
			get
			{
				return this._observacoesProcesso;
			}
			set
			{
				if ((this._observacoesProcesso != value))
				{
					this._observacoesProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacaoProcesso", DbType="VarChar(50)")]
		public string situacaoProcesso
		{
			get
			{
				return this._situacaoProcesso;
			}
			set
			{
				if ((this._situacaoProcesso != value))
				{
					this._situacaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataProcesso", DbType="Char(30)")]
		public string dataProcesso
		{
			get
			{
				return this._dataProcesso;
			}
			set
			{
				if ((this._dataProcesso != value))
				{
					this._dataProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="VarChar(3)")]
		public string codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminhoProcesso", DbType="VarChar(250)")]
		public string caminhoProcesso
		{
			get
			{
				return this._caminhoProcesso;
			}
			set
			{
				if ((this._caminhoProcesso != value))
				{
					this._caminhoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoArquivoDownload", DbType="VarChar(1000)")]
		public string descricaoArquivoDownload
		{
			get
			{
				return this._descricaoArquivoDownload;
			}
			set
			{
				if ((this._descricaoArquivoDownload != value))
				{
					this._descricaoArquivoDownload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_licitacoes_avisos")]
	public partial class vw_licitacoes_aviso
	{
		
		private string _menu;
		
		private System.Nullable<int> _anoProcesso;
		
		private string _descricaoProcesso;
		
		private string _observacoesProcesso;
		
		private string _situacaoProcesso;
		
		private string _dataProcesso;
		
		private string _codigoProcesso;
		
		private string _caminhoProcesso;
		
		private string _descricaoArquivoDownload;
		
		public vw_licitacoes_aviso()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					this._menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoProcesso", DbType="Int")]
		public System.Nullable<int> anoProcesso
		{
			get
			{
				return this._anoProcesso;
			}
			set
			{
				if ((this._anoProcesso != value))
				{
					this._anoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoProcesso", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descricaoProcesso
		{
			get
			{
				return this._descricaoProcesso;
			}
			set
			{
				if ((this._descricaoProcesso != value))
				{
					this._descricaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoesProcesso", DbType="VarChar(MAX)")]
		public string observacoesProcesso
		{
			get
			{
				return this._observacoesProcesso;
			}
			set
			{
				if ((this._observacoesProcesso != value))
				{
					this._observacoesProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacaoProcesso", DbType="VarChar(50)")]
		public string situacaoProcesso
		{
			get
			{
				return this._situacaoProcesso;
			}
			set
			{
				if ((this._situacaoProcesso != value))
				{
					this._situacaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataProcesso", DbType="Char(30)")]
		public string dataProcesso
		{
			get
			{
				return this._dataProcesso;
			}
			set
			{
				if ((this._dataProcesso != value))
				{
					this._dataProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="VarChar(3)")]
		public string codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminhoProcesso", DbType="VarChar(250)")]
		public string caminhoProcesso
		{
			get
			{
				return this._caminhoProcesso;
			}
			set
			{
				if ((this._caminhoProcesso != value))
				{
					this._caminhoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoArquivoDownload", DbType="VarChar(1000)")]
		public string descricaoArquivoDownload
		{
			get
			{
				return this._descricaoArquivoDownload;
			}
			set
			{
				if ((this._descricaoArquivoDownload != value))
				{
					this._descricaoArquivoDownload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_licitacoes_tomada_de_precos")]
	public partial class vw_licitacoes_tomada_de_preco
	{
		
		private string _menu;
		
		private System.Nullable<int> _anoProcesso;
		
		private string _descricaoProcesso;
		
		private string _observacoesProcesso;
		
		private string _situacaoProcesso;
		
		private string _dataProcesso;
		
		private string _codigoProcesso;
		
		private string _caminhoProcesso;
		
		private string _descricaoArquivoDownload;
		
		public vw_licitacoes_tomada_de_preco()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					this._menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoProcesso", DbType="Int")]
		public System.Nullable<int> anoProcesso
		{
			get
			{
				return this._anoProcesso;
			}
			set
			{
				if ((this._anoProcesso != value))
				{
					this._anoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoProcesso", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descricaoProcesso
		{
			get
			{
				return this._descricaoProcesso;
			}
			set
			{
				if ((this._descricaoProcesso != value))
				{
					this._descricaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoesProcesso", DbType="VarChar(MAX)")]
		public string observacoesProcesso
		{
			get
			{
				return this._observacoesProcesso;
			}
			set
			{
				if ((this._observacoesProcesso != value))
				{
					this._observacoesProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacaoProcesso", DbType="VarChar(50)")]
		public string situacaoProcesso
		{
			get
			{
				return this._situacaoProcesso;
			}
			set
			{
				if ((this._situacaoProcesso != value))
				{
					this._situacaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataProcesso", DbType="Char(30)")]
		public string dataProcesso
		{
			get
			{
				return this._dataProcesso;
			}
			set
			{
				if ((this._dataProcesso != value))
				{
					this._dataProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="VarChar(3)")]
		public string codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminhoProcesso", DbType="VarChar(250)")]
		public string caminhoProcesso
		{
			get
			{
				return this._caminhoProcesso;
			}
			set
			{
				if ((this._caminhoProcesso != value))
				{
					this._caminhoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoArquivoDownload", DbType="VarChar(1000)")]
		public string descricaoArquivoDownload
		{
			get
			{
				return this._descricaoArquivoDownload;
			}
			set
			{
				if ((this._descricaoArquivoDownload != value))
				{
					this._descricaoArquivoDownload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_licitacoes_concorrencia_publica")]
	public partial class vw_licitacoes_concorrencia_publica
	{
		
		private string _menu;
		
		private System.Nullable<int> _anoProcesso;
		
		private string _descricaoProcesso;
		
		private string _observacoesProcesso;
		
		private string _situacaoProcesso;
		
		private string _dataProcesso;
		
		private string _codigoProcesso;
		
		private string _caminhoProcesso;
		
		private string _descricaoArquivoDownload;
		
		public vw_licitacoes_concorrencia_publica()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					this._menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoProcesso", DbType="Int")]
		public System.Nullable<int> anoProcesso
		{
			get
			{
				return this._anoProcesso;
			}
			set
			{
				if ((this._anoProcesso != value))
				{
					this._anoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoProcesso", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descricaoProcesso
		{
			get
			{
				return this._descricaoProcesso;
			}
			set
			{
				if ((this._descricaoProcesso != value))
				{
					this._descricaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoesProcesso", DbType="VarChar(MAX)")]
		public string observacoesProcesso
		{
			get
			{
				return this._observacoesProcesso;
			}
			set
			{
				if ((this._observacoesProcesso != value))
				{
					this._observacoesProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacaoProcesso", DbType="VarChar(50)")]
		public string situacaoProcesso
		{
			get
			{
				return this._situacaoProcesso;
			}
			set
			{
				if ((this._situacaoProcesso != value))
				{
					this._situacaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataProcesso", DbType="Char(30)")]
		public string dataProcesso
		{
			get
			{
				return this._dataProcesso;
			}
			set
			{
				if ((this._dataProcesso != value))
				{
					this._dataProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="VarChar(3)")]
		public string codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminhoProcesso", DbType="VarChar(250)")]
		public string caminhoProcesso
		{
			get
			{
				return this._caminhoProcesso;
			}
			set
			{
				if ((this._caminhoProcesso != value))
				{
					this._caminhoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoArquivoDownload", DbType="VarChar(1000)")]
		public string descricaoArquivoDownload
		{
			get
			{
				return this._descricaoArquivoDownload;
			}
			set
			{
				if ((this._descricaoArquivoDownload != value))
				{
					this._descricaoArquivoDownload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_licitacoes_pregao_presencial")]
	public partial class vw_licitacoes_pregao_presencial
	{
		
		private string _menu;
		
		private System.Nullable<int> _anoProcesso;
		
		private string _descricaoProcesso;
		
		private string _observacoesProcesso;
		
		private string _situacaoProcesso;
		
		private string _dataProcesso;
		
		private string _codigoProcesso;
		
		private string _caminho;
		
		private string _caminhoProcesso;
		
		private string _descricaoArquivoDownload;
		
		public vw_licitacoes_pregao_presencial()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					this._menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoProcesso", DbType="Int")]
		public System.Nullable<int> anoProcesso
		{
			get
			{
				return this._anoProcesso;
			}
			set
			{
				if ((this._anoProcesso != value))
				{
					this._anoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoProcesso", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descricaoProcesso
		{
			get
			{
				return this._descricaoProcesso;
			}
			set
			{
				if ((this._descricaoProcesso != value))
				{
					this._descricaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoesProcesso", DbType="VarChar(MAX)")]
		public string observacoesProcesso
		{
			get
			{
				return this._observacoesProcesso;
			}
			set
			{
				if ((this._observacoesProcesso != value))
				{
					this._observacoesProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacaoProcesso", DbType="VarChar(50)")]
		public string situacaoProcesso
		{
			get
			{
				return this._situacaoProcesso;
			}
			set
			{
				if ((this._situacaoProcesso != value))
				{
					this._situacaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataProcesso", DbType="Char(30)")]
		public string dataProcesso
		{
			get
			{
				return this._dataProcesso;
			}
			set
			{
				if ((this._dataProcesso != value))
				{
					this._dataProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="VarChar(3)")]
		public string codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminho", DbType="VarChar(500)")]
		public string caminho
		{
			get
			{
				return this._caminho;
			}
			set
			{
				if ((this._caminho != value))
				{
					this._caminho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminhoProcesso", DbType="VarChar(250)")]
		public string caminhoProcesso
		{
			get
			{
				return this._caminhoProcesso;
			}
			set
			{
				if ((this._caminhoProcesso != value))
				{
					this._caminhoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoArquivoDownload", DbType="VarChar(1000)")]
		public string descricaoArquivoDownload
		{
			get
			{
				return this._descricaoArquivoDownload;
			}
			set
			{
				if ((this._descricaoArquivoDownload != value))
				{
					this._descricaoArquivoDownload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_licitacoes_pregao_presencial_registro_precos")]
	public partial class vw_licitacoes_pregao_presencial_registro_preco
	{
		
		private string _menu;
		
		private System.Nullable<int> _anoProcesso;
		
		private string _descricaoProcesso;
		
		private string _observacoesProcesso;
		
		private string _situacaoProcesso;
		
		private string _dataProcesso;
		
		private string _codigoProcesso;
		
		private string _caminho;
		
		private string _caminhoProcesso;
		
		private string _descricaoArquivoDownload;
		
		public vw_licitacoes_pregao_presencial_registro_preco()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					this._menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoProcesso", DbType="Int")]
		public System.Nullable<int> anoProcesso
		{
			get
			{
				return this._anoProcesso;
			}
			set
			{
				if ((this._anoProcesso != value))
				{
					this._anoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoProcesso", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descricaoProcesso
		{
			get
			{
				return this._descricaoProcesso;
			}
			set
			{
				if ((this._descricaoProcesso != value))
				{
					this._descricaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoesProcesso", DbType="VarChar(MAX)")]
		public string observacoesProcesso
		{
			get
			{
				return this._observacoesProcesso;
			}
			set
			{
				if ((this._observacoesProcesso != value))
				{
					this._observacoesProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacaoProcesso", DbType="VarChar(50)")]
		public string situacaoProcesso
		{
			get
			{
				return this._situacaoProcesso;
			}
			set
			{
				if ((this._situacaoProcesso != value))
				{
					this._situacaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataProcesso", DbType="Char(30)")]
		public string dataProcesso
		{
			get
			{
				return this._dataProcesso;
			}
			set
			{
				if ((this._dataProcesso != value))
				{
					this._dataProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="VarChar(3)")]
		public string codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminho", DbType="VarChar(500)")]
		public string caminho
		{
			get
			{
				return this._caminho;
			}
			set
			{
				if ((this._caminho != value))
				{
					this._caminho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminhoProcesso", DbType="VarChar(250)")]
		public string caminhoProcesso
		{
			get
			{
				return this._caminhoProcesso;
			}
			set
			{
				if ((this._caminhoProcesso != value))
				{
					this._caminhoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoArquivoDownload", DbType="VarChar(1000)")]
		public string descricaoArquivoDownload
		{
			get
			{
				return this._descricaoArquivoDownload;
			}
			set
			{
				if ((this._descricaoArquivoDownload != value))
				{
					this._descricaoArquivoDownload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_licitacoes_pregao_eletronico")]
	public partial class vw_licitacoes_pregao_eletronico
	{
		
		private string _menu;
		
		private System.Nullable<int> _anoProcesso;
		
		private string _descricaoProcesso;
		
		private string _observacoesProcesso;
		
		private string _situacaoProcesso;
		
		private string _dataProcesso;
		
		private string _codigoProcesso;
		
		private string _caminho;
		
		private string _caminhoProcesso;
		
		private string _descricaoArquivoDownload;
		
		public vw_licitacoes_pregao_eletronico()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					this._menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoProcesso", DbType="Int")]
		public System.Nullable<int> anoProcesso
		{
			get
			{
				return this._anoProcesso;
			}
			set
			{
				if ((this._anoProcesso != value))
				{
					this._anoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoProcesso", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descricaoProcesso
		{
			get
			{
				return this._descricaoProcesso;
			}
			set
			{
				if ((this._descricaoProcesso != value))
				{
					this._descricaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoesProcesso", DbType="VarChar(MAX)")]
		public string observacoesProcesso
		{
			get
			{
				return this._observacoesProcesso;
			}
			set
			{
				if ((this._observacoesProcesso != value))
				{
					this._observacoesProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacaoProcesso", DbType="VarChar(50)")]
		public string situacaoProcesso
		{
			get
			{
				return this._situacaoProcesso;
			}
			set
			{
				if ((this._situacaoProcesso != value))
				{
					this._situacaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataProcesso", DbType="Char(30)")]
		public string dataProcesso
		{
			get
			{
				return this._dataProcesso;
			}
			set
			{
				if ((this._dataProcesso != value))
				{
					this._dataProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="VarChar(3)")]
		public string codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminho", DbType="VarChar(500)")]
		public string caminho
		{
			get
			{
				return this._caminho;
			}
			set
			{
				if ((this._caminho != value))
				{
					this._caminho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminhoProcesso", DbType="VarChar(250)")]
		public string caminhoProcesso
		{
			get
			{
				return this._caminhoProcesso;
			}
			set
			{
				if ((this._caminhoProcesso != value))
				{
					this._caminhoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoArquivoDownload", DbType="VarChar(1000)")]
		public string descricaoArquivoDownload
		{
			get
			{
				return this._descricaoArquivoDownload;
			}
			set
			{
				if ((this._descricaoArquivoDownload != value))
				{
					this._descricaoArquivoDownload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_licitacoes_ata_registro_precos")]
	public partial class vw_licitacoes_ata_registro_preco
	{
		
		private string _menu;
		
		private string _anoProcesso;
		
		private string _descricaoProcesso;
		
		private string _observacoesProcesso;
		
		private string _situacaoProcesso;
		
		private string _dataProcesso;
		
		private string _codigoProcesso;
		
		private string _caminho;
		
		private string _caminhoProcesso;
		
		private string _descricaoArquivoDownload;
		
		public vw_licitacoes_ata_registro_preco()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					this._menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoProcesso", DbType="VarChar(4)")]
		public string anoProcesso
		{
			get
			{
				return this._anoProcesso;
			}
			set
			{
				if ((this._anoProcesso != value))
				{
					this._anoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoProcesso", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descricaoProcesso
		{
			get
			{
				return this._descricaoProcesso;
			}
			set
			{
				if ((this._descricaoProcesso != value))
				{
					this._descricaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoesProcesso", DbType="VarChar(MAX)")]
		public string observacoesProcesso
		{
			get
			{
				return this._observacoesProcesso;
			}
			set
			{
				if ((this._observacoesProcesso != value))
				{
					this._observacoesProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacaoProcesso", DbType="VarChar(50)")]
		public string situacaoProcesso
		{
			get
			{
				return this._situacaoProcesso;
			}
			set
			{
				if ((this._situacaoProcesso != value))
				{
					this._situacaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataProcesso", DbType="Char(30)")]
		public string dataProcesso
		{
			get
			{
				return this._dataProcesso;
			}
			set
			{
				if ((this._dataProcesso != value))
				{
					this._dataProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="VarChar(3)")]
		public string codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminho", DbType="VarChar(500)")]
		public string caminho
		{
			get
			{
				return this._caminho;
			}
			set
			{
				if ((this._caminho != value))
				{
					this._caminho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminhoProcesso", DbType="VarChar(250)")]
		public string caminhoProcesso
		{
			get
			{
				return this._caminhoProcesso;
			}
			set
			{
				if ((this._caminhoProcesso != value))
				{
					this._caminhoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoArquivoDownload", DbType="VarChar(1000)")]
		public string descricaoArquivoDownload
		{
			get
			{
				return this._descricaoArquivoDownload;
			}
			set
			{
				if ((this._descricaoArquivoDownload != value))
				{
					this._descricaoArquivoDownload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_licitacoes_cadastro_fornecedores")]
	public partial class vw_licitacoes_cadastro_fornecedore
	{
		
		private string _menu;
		
		private string _anoProcesso;
		
		private string _descricaoProcesso;
		
		private string _observacoesProcesso;
		
		private string _situacaoProcesso;
		
		private string _dataProcesso;
		
		private string _codigoProcesso;
		
		private string _caminho;
		
		private string _caminhoProcesso;
		
		private string _descricaoArquivoDownload;
		
		public vw_licitacoes_cadastro_fornecedore()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					this._menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoProcesso", DbType="VarChar(4)")]
		public string anoProcesso
		{
			get
			{
				return this._anoProcesso;
			}
			set
			{
				if ((this._anoProcesso != value))
				{
					this._anoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoProcesso", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descricaoProcesso
		{
			get
			{
				return this._descricaoProcesso;
			}
			set
			{
				if ((this._descricaoProcesso != value))
				{
					this._descricaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoesProcesso", DbType="VarChar(MAX)")]
		public string observacoesProcesso
		{
			get
			{
				return this._observacoesProcesso;
			}
			set
			{
				if ((this._observacoesProcesso != value))
				{
					this._observacoesProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacaoProcesso", DbType="VarChar(50)")]
		public string situacaoProcesso
		{
			get
			{
				return this._situacaoProcesso;
			}
			set
			{
				if ((this._situacaoProcesso != value))
				{
					this._situacaoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataProcesso", DbType="Char(30)")]
		public string dataProcesso
		{
			get
			{
				return this._dataProcesso;
			}
			set
			{
				if ((this._dataProcesso != value))
				{
					this._dataProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcesso", DbType="VarChar(3)")]
		public string codigoProcesso
		{
			get
			{
				return this._codigoProcesso;
			}
			set
			{
				if ((this._codigoProcesso != value))
				{
					this._codigoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminho", DbType="VarChar(500)")]
		public string caminho
		{
			get
			{
				return this._caminho;
			}
			set
			{
				if ((this._caminho != value))
				{
					this._caminho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caminhoProcesso", DbType="VarChar(250)")]
		public string caminhoProcesso
		{
			get
			{
				return this._caminhoProcesso;
			}
			set
			{
				if ((this._caminhoProcesso != value))
				{
					this._caminhoProcesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoArquivoDownload", DbType="VarChar(1000)")]
		public string descricaoArquivoDownload
		{
			get
			{
				return this._descricaoArquivoDownload;
			}
			set
			{
				if ((this._descricaoArquivoDownload != value))
				{
					this._descricaoArquivoDownload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_folha_pagamento_servidor")]
	public partial class vw_folha_pagamento_servidor
	{
		
		private string _mesCompetencia;
		
		private System.Nullable<int> _anoCompetencia;
		
		private string _matricula;
		
		private string _nomeBeneficiario;
		
		private string _cargo;
		
		private string _classe;
		
		private string _cargoComissao;
		
		private System.Nullable<decimal> _vencimento;
		
		private System.Nullable<decimal> _subsidio;
		
		private System.Nullable<decimal> _vantagemsPessoais;
		
		private System.Nullable<decimal> _vantagensCargo;
		
		private System.Nullable<decimal> _ferias;
		
		private System.Nullable<decimal> _decimoSalario;
		
		private System.Nullable<decimal> _totalCredito;
		
		private System.Nullable<decimal> _previdencia;
		
		private System.Nullable<decimal> _imposto;
		
		private System.Nullable<decimal> _totalDesconto;
		
		private System.Nullable<decimal> _totalLiquido;
		
		private System.Nullable<decimal> _indenizacoes;
		
		public vw_folha_pagamento_servidor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesCompetencia", DbType="VarChar(15)")]
		public string mesCompetencia
		{
			get
			{
				return this._mesCompetencia;
			}
			set
			{
				if ((this._mesCompetencia != value))
				{
					this._mesCompetencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoCompetencia", DbType="Int")]
		public System.Nullable<int> anoCompetencia
		{
			get
			{
				return this._anoCompetencia;
			}
			set
			{
				if ((this._anoCompetencia != value))
				{
					this._anoCompetencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="VarChar(255)")]
		public string matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					this._matricula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeBeneficiario", DbType="VarChar(255)")]
		public string nomeBeneficiario
		{
			get
			{
				return this._nomeBeneficiario;
			}
			set
			{
				if ((this._nomeBeneficiario != value))
				{
					this._nomeBeneficiario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(255)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this._cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe", DbType="VarChar(255)")]
		public string classe
		{
			get
			{
				return this._classe;
			}
			set
			{
				if ((this._classe != value))
				{
					this._classe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargoComissao", DbType="VarChar(255)")]
		public string cargoComissao
		{
			get
			{
				return this._cargoComissao;
			}
			set
			{
				if ((this._cargoComissao != value))
				{
					this._cargoComissao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimento", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> vencimento
		{
			get
			{
				return this._vencimento;
			}
			set
			{
				if ((this._vencimento != value))
				{
					this._vencimento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subsidio", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> subsidio
		{
			get
			{
				return this._subsidio;
			}
			set
			{
				if ((this._subsidio != value))
				{
					this._subsidio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vantagemsPessoais", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> vantagemsPessoais
		{
			get
			{
				return this._vantagemsPessoais;
			}
			set
			{
				if ((this._vantagemsPessoais != value))
				{
					this._vantagemsPessoais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vantagensCargo", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> vantagensCargo
		{
			get
			{
				return this._vantagensCargo;
			}
			set
			{
				if ((this._vantagensCargo != value))
				{
					this._vantagensCargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ferias", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> ferias
		{
			get
			{
				return this._ferias;
			}
			set
			{
				if ((this._ferias != value))
				{
					this._ferias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decimoSalario", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> decimoSalario
		{
			get
			{
				return this._decimoSalario;
			}
			set
			{
				if ((this._decimoSalario != value))
				{
					this._decimoSalario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalCredito", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> totalCredito
		{
			get
			{
				return this._totalCredito;
			}
			set
			{
				if ((this._totalCredito != value))
				{
					this._totalCredito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_previdencia", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> previdencia
		{
			get
			{
				return this._previdencia;
			}
			set
			{
				if ((this._previdencia != value))
				{
					this._previdencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imposto", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> imposto
		{
			get
			{
				return this._imposto;
			}
			set
			{
				if ((this._imposto != value))
				{
					this._imposto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalDesconto", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> totalDesconto
		{
			get
			{
				return this._totalDesconto;
			}
			set
			{
				if ((this._totalDesconto != value))
				{
					this._totalDesconto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalLiquido", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> totalLiquido
		{
			get
			{
				return this._totalLiquido;
			}
			set
			{
				if ((this._totalLiquido != value))
				{
					this._totalLiquido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indenizacoes", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> indenizacoes
		{
			get
			{
				return this._indenizacoes;
			}
			set
			{
				if ((this._indenizacoes != value))
				{
					this._indenizacoes = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_servidores")]
	public partial class vw_servidore
	{
		
		private string _matricula;
		
		private string _nomeBeneficiario;
		
		public vw_servidore()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="VarChar(255)")]
		public string matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					this._matricula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeBeneficiario", DbType="VarChar(255)")]
		public string nomeBeneficiario
		{
			get
			{
				return this._nomeBeneficiario;
			}
			set
			{
				if ((this._nomeBeneficiario != value))
				{
					this._nomeBeneficiario = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
