<?xml version="1.0" encoding="utf-8"?><Database Name="bd_Defensoria_Transparencia" Class="TransparenciaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=s744;Initial Catalog=bd_Defensoria_Transparencia;Persist Security Info=True;User ID=sa" SettingsObjectName="TransparenciaDAO.Properties.Settings" SettingsPropertyName="bd_Defensoria_TransparenciaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vw_contratos_convenios" Member="vw_contratos_convenios">
    <Type Name="vw_contratos_convenio">
      <Column Name="codigoProcesso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomeArquivoPDF" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ano" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="numeroProcesso" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contratada" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="modalidade" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="finalizado" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="vigenciaInicial" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="vigenciaFinal" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="dataContrato" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="vigenciaProrrogada" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="objeto" Type="System.String" DbType="VarChar(5000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_cargo_comissao_servidor" Member="vw_cargo_comissao_servidors">
    <Type Name="vw_cargo_comissao_servidor">
      <Column Name="grupo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="simbolo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cargo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="vagasPrevistas" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_cargo_defensor_servidor" Member="vw_cargo_defensor_servidors">
    <Type Name="vw_cargo_defensor_servidor">
      <Column Name="carreira" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cargo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="classe" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="simbolo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="vagasPreenchidas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="previstas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nomeBeneficiario" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="matricula" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_cargo_efetivo_servidor" Member="vw_cargo_efetivo_servidors">
    <Type Name="vw_cargo_efetivo_servidor">
      <Column Name="carreira" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="quantitativo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="classe" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_folha_subsidio" Member="vw_folha_subsidios">
    <Type Name="vw_folha_subsidio">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="descricaoClasse" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="tipoServidor" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="valorReajuste" Type="System.Decimal" DbType="Decimal(19,2)" CanBeNull="true" />
      <Column Name="anoCompetencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vagasPrevistas" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_cargo_efetivo_vencimento" Member="vw_cargo_efetivo_vencimentos">
    <Type Name="vw_cargo_efetivo_vencimento">
      <Column Name="anoCompetencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="classe" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="vencimentoBase" Type="System.Decimal" DbType="Decimal(19,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_cargo_comissionado_vencimento" Member="vw_cargo_comissionado_vencimentos">
    <Type Name="vw_cargo_comissionado_vencimento">
      <Column Name="anoCompetencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descricaoClasse" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="tipoServidor" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="valorReajuste" Type="System.Decimal" DbType="Decimal(19,2)" CanBeNull="true" />
      <Column Name="gratificacao" Type="System.Decimal" DbType="Decimal(19,2)" CanBeNull="true" />
      <Column Name="percentual" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_licitacoes_legislacao" Member="vw_licitacoes_legislacaos">
    <Type Name="vw_licitacoes_legislacao">
      <Column Name="menu" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="anoProcesso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descricaoProcesso" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="observacoesProcesso" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="situacaoProcesso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dataProcesso" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="codigoProcesso" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="caminhoProcesso" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="descricaoArquivoDownload" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_licitacoes_avisos" Member="vw_licitacoes_avisos">
    <Type Name="vw_licitacoes_aviso">
      <Column Name="menu" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="anoProcesso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descricaoProcesso" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="observacoesProcesso" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="situacaoProcesso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dataProcesso" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="codigoProcesso" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="caminhoProcesso" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="descricaoArquivoDownload" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_licitacoes_tomada_de_precos" Member="vw_licitacoes_tomada_de_precos">
    <Type Name="vw_licitacoes_tomada_de_preco">
      <Column Name="menu" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="anoProcesso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descricaoProcesso" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="observacoesProcesso" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="situacaoProcesso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dataProcesso" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="codigoProcesso" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="caminhoProcesso" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="descricaoArquivoDownload" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_licitacoes_concorrencia_publica" Member="vw_licitacoes_concorrencia_publicas">
    <Type Name="vw_licitacoes_concorrencia_publica">
      <Column Name="menu" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="anoProcesso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descricaoProcesso" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="observacoesProcesso" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="situacaoProcesso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dataProcesso" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="codigoProcesso" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="caminhoProcesso" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="descricaoArquivoDownload" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_licitacoes_pregao_presencial" Member="vw_licitacoes_pregao_presencials">
    <Type Name="vw_licitacoes_pregao_presencial">
      <Column Name="menu" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="anoProcesso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descricaoProcesso" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="observacoesProcesso" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="situacaoProcesso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dataProcesso" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="codigoProcesso" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="caminho" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="caminhoProcesso" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="descricaoArquivoDownload" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_licitacoes_pregao_presencial_registro_precos" Member="vw_licitacoes_pregao_presencial_registro_precos">
    <Type Name="vw_licitacoes_pregao_presencial_registro_preco">
      <Column Name="menu" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="anoProcesso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descricaoProcesso" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="observacoesProcesso" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="situacaoProcesso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dataProcesso" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="codigoProcesso" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="caminho" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="caminhoProcesso" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="descricaoArquivoDownload" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_licitacoes_pregao_eletronico" Member="vw_licitacoes_pregao_eletronicos">
    <Type Name="vw_licitacoes_pregao_eletronico">
      <Column Name="menu" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="anoProcesso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descricaoProcesso" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="observacoesProcesso" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="situacaoProcesso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dataProcesso" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="codigoProcesso" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="caminho" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="caminhoProcesso" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="descricaoArquivoDownload" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_licitacoes_ata_registro_precos" Member="vw_licitacoes_ata_registro_precos">
    <Type Name="vw_licitacoes_ata_registro_preco">
      <Column Name="menu" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="anoProcesso" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="descricaoProcesso" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="observacoesProcesso" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="situacaoProcesso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dataProcesso" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="codigoProcesso" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="caminho" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="caminhoProcesso" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="descricaoArquivoDownload" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_licitacoes_cadastro_fornecedores" Member="vw_licitacoes_cadastro_fornecedores">
    <Type Name="vw_licitacoes_cadastro_fornecedore">
      <Column Name="menu" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="anoProcesso" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="descricaoProcesso" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="observacoesProcesso" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="situacaoProcesso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dataProcesso" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="codigoProcesso" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="caminho" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="caminhoProcesso" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="descricaoArquivoDownload" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_servidores" Member="vw_servidores">
    <Type Name="vw_servidore">
      <Column Name="matricula" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="nomeBeneficiario" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_folha_consulta_remuneracao_servidor" Member="vw_folha_consulta_remuneracao_servidors">
    <Type Name="vw_folha_consulta_remuneracao_servidor">
      <Column Name="mesCompetencia" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="anoCompetencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="matricula" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="nomeBeneficiario" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cargo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="classe" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cargoComissao" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="vencimento" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="subsidio" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="vantagensPessoais" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="vantagensCargo" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="ferias" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="decimoSalario" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="totalCredito" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="previdencia" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="imposto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="totalDesconto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="totalLiquido" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="indenizacoes" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Temporalidade" Member="tbl_Temporalidades">
    <Type Name="tbl_Temporalidade">
      <Column Name="cod" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numeroProcesso" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="contratada" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="codTabTemp" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.pr_folha_pagamento_servidores" Method="pr_folha_pagamento_servidores">
    <Parameter Name="mes" Type="System.Int32" DbType="Int" />
    <Parameter Name="ano" Type="System.Int32" DbType="Int" />
    <ElementType Name="pr_folha_pagamento_servidoresResult">
      <Column Name="mesCompetencia" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="anoCompetencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nomeBeneficiario" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="matricula" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="categoriaServidor" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cargo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="classe" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cargoComissao" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="subsidio" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="vencimento" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="vantagemsPessoais" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="vantagensCargo" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="ferias" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="decimoSalario" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="totalCredito" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="previdencia" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="imposto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="totalDesconto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="rendimentoLiquido" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="indenizacoes" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>